version: '3.3'
services:
  db:
    build:
      context: "."
      dockerfile: "db.Dockerfile"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: realtime_quiz_app
    ports:
      - 5432:5432
    volumes:
      - realtime-quiz-app-data:/var/lib/postgresql/data
    networks:
      - default_network
networks:
  default_network:
volumes:
  realtime-quiz-app-data:
    external: true